/**
 * 자동화 입력 스크립트
 * how to execute? `node booking-anyone.js`
 */

const url = 'http://localhost:3001/v1';
const data = [
  {
    uri: `schools`,
    payload: {
      name: '삼척초등학교',
      authorityCode: 'K10',
      region: 'GANGWON',
      schoolCode: '7872025',
      address: '강원특별자치도 삼척시 일반로 273',
    },
  },
  {
    uri: `terms`,
    payload: {
      schoolId: 1,
      schoolYear: 2025,
      schoolName: '삼척초등학교',
      termName: '봄학기',
      start: '2025-03-12',
      end: '2025-07-25',
    },
  },
  {
    uri: `categories/seed`,
    payload: {},
  },
  {
    uri: `schools/1/students/bulk/seed`,
    payload: {},
  },
  {
    uri: `schools/1/calendars`,
    payload: {},
  },
  {
    uri: `schools/1/terms/1/lessons/bulk`,
    payload: [
      {
        lessonName: '바이올린',
        description: '바이올린 기본 및 연주곡 기본 익히기',
        instructorFee: 30000,
        bookFees: [{ name: '바이올린교재', amount: 17000 }],
        materialFees: [],
        note: '교재비만 있는 수업',
        categoryId: 1,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '김사과',
            instructorPhone: '01024820001',
            groupName: '바이올린:화요일A반',
            location: '과학실2',
            capacity: 10,
            allowedGrades: '1~2',
            weekday: '화',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '바이올린:화요일B반',
            location: '과학실2',
            capacity: 10,
            allowedGrades: '3~6',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '교육보드게임',
        description: '교육보드게임',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '교재비와 재료비가 없는 수업',
        categoryId: 1,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '교육보드게임:목요일A반',
            location: '과학실2',
            capacity: 20,
            allowedGrades: '2',
            weekday: '목',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '교육보드게임:목요일B반',
            location: '과학실2',
            capacity: 20,
            allowedGrades: '1',
            weekday: '목',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '교육보드게임:목요일C반',
            location: '과학실2',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '목',
            start: '3:30pm',
            end: '4:10pm',
          },
        ],
      },
      {
        lessonName: '창의독서',
        description: '창의독서',
        instructorFee: 30000,
        bookFees: [{ name: '독서교재비', amount: 7000 }],
        materialFees: [{ name: '독서재료비', amount: 5000 }],
        note: '교재비와 재료비가 있는 수업',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '창의독서:월요일A반',
            location: '도서관',
            capacity: 20,
            allowedGrades: '1',
            weekday: '월',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '창의독서:월요일B반',
            location: '도서관',
            capacity: 20,
            allowedGrades: '2',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '창의독서:금요일A반',
            location: '도서관',
            capacity: 20,
            allowedGrades: '1',
            weekday: '금',
            start: '1:00pm',
            end: '1:40pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '창의독서:금요일B반',
            location: '도서관',
            capacity: 20,
            allowedGrades: '2',
            weekday: '금',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '창의독서:금요일C반',
            location: '도서관',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '금',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '중국어',
        description: '중국어 기초발음 및 회화',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '교재비와 재료비가 없는 수업',
        categoryId: 1,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '중국어:금요일A반',
            location: '과학실2',
            capacity: 16,
            allowedGrades: '1',
            weekday: '금',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '중국어:금요일B반',
            location: '과학실2',
            capacity: 16,
            allowedGrades: '2',
            weekday: '금',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '중국어:금요일C반',
            location: '과학실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '3:30pm',
            end: '4:10pm',
          },
        ],
      },
      {
        lessonName: '주산과 암산',
        description: '수학학습의 연산능력 강화 및 집중력 훈련',
        instructorFee: 30000,
        bookFees: [
          { name: '기초~4급', amount: 10000 },
          { name: '3급~단급', amount: 12000 },
        ],
        materialFees: [],
        note: '교재비와 재료비가 있는 수업',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:화요일A반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '1',
            weekday: '화',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:화요일B반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '2',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:화요일C반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '화',
            start: '3:30pm',
            end: '4:10pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:목요일A반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '1',
            weekday: '목',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:목요일B반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '2',
            weekday: '목',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '주산과 암산:목요일C반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '목',
            start: '3:30pm',
            end: '4:10pm',
          },
        ],
      },
      {
        lessonName: '로봇과학',
        description: '로봇으로 배우는 재미있는 과학원리',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [
          { name: '1단계', amount: 92000 },
          { name: '2단계', amount: 122000 },
          { name: '3단계', amount: 92000 },
          { name: '4단계', amount: 92000 },
          { name: '5단계', amount: 92000 },
          { name: '6단계', amount: 92000 },
          { name: '7단계', amount: 122000 },
          { name: '8단계', amount: 92000 },
        ],
        note: '재료비만 있는 수업',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '로봇과학:수요일A반',
            location: '과학실2',
            capacity: 18,
            allowedGrades: '1~2',
            weekday: '수',
            start: '1:00pm',
            end: '2:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '로봇과학:수요일B반',
            location: '과학실2',
            capacity: 18,
            allowedGrades: '3~6',
            weekday: '수',
            start: '2:30pm',
            end: '3:50pm',
          },
        ],
      },
      {
        lessonName: '클레이&아트',
        description: '아이들의 창의력을 쑥쑥 자라게 하는 재미있는 클레이 수업',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [{ name: '재료비', amount: 16000 }],
        note: '재료비만 있는 수업',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '클레이&아트:수요일A반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '1',
            weekday: '수',
            start: '1:00pm',
            end: '1:40pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '클레이&아트:수요일B반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '2',
            weekday: '수',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '클레이&아트:수요일C반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '수',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '클레이&아트:금요일D반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '1',
            weekday: '금',
            start: '1:00pm',
            end: '1:40pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '클레이&아트:금요일E반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '2',
            weekday: '금',
            start: '1:50pm',
            end: '2:30pm',
          },
        ],
      },
      {
        lessonName: '놀이체육',
        description: '놀면서 체력강화',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '교재비와 재료비가 없는 수업',
        categoryId: 1,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:월요일A반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '1',
            weekday: '월',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:월요일B반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '2',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:화요일C반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '1',
            weekday: '화',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:화요일D반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '2',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:수요일E반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '2',
            weekday: '수',
            start: '1:00pm',
            end: '1:40pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '놀이체육:수요일F반',
            location: '나눔의 터',
            capacity: 16,
            allowedGrades: '1',
            weekday: '수',
            start: '1:50pm',
            end: '2:30pm',
          },
        ],
      },
      {
        lessonName: '미술',
        description: '회화 위주 미술 수업',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [{ name: '미술재료비', amount: 10000 }],
        note: '재료비만 있는 수업',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '미술:월요일A반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '1~2',
            weekday: '월',
            start: '1:50pm',
            end: '2:50pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '미술:월요일B반',
            location: '과학실1',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '월',
            start: '3:00pm',
            end: '4:00pm',
          },
        ],
      },
      {
        lessonName: '배드민턴 & 뉴스포츠',
        description: '매드민턴 익히기 / 뉴스포츠 배우기',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '배드민턴 라켓, 샤틀콕 개별준비',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '배드민턴 & 뉴스포츠:월요일A반',
            location: '나눔의 터',
            capacity: 15,
            allowedGrades: '3~4',
            weekday: '월',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '배드민턴 & 뉴스포츠:월요일B반',
            location: '나눔의 터',
            capacity: 15,
            allowedGrades: '5~6',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '배드민턴 & 뉴스포츠:수요일A반',
            location: '체육관',
            capacity: 15,
            allowedGrades: '3~4',
            weekday: '수',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '배드민턴 & 뉴스포츠:수요일B반',
            location: '체육관',
            capacity: 15,
            allowedGrades: '5~6',
            weekday: '수',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '축구',
        description: '축구 기본기 및 플레이 방법 배우기',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '편한 운동화',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '축구:월요일A반',
            location: '운동장',
            capacity: 30,
            allowedGrades: '3~6',
            weekday: '월',
            start: '2:40pm',
            end: '4:00pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '축구:수요일A반',
            location: '운동장',
            capacity: 30,
            allowedGrades: '3~6',
            weekday: '수',
            start: '2:40pm',
            end: '4:00pm',
          },
        ],
      },
      {
        lessonName: '컴퓨터',
        description: '컴퓨터 배우기',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '편한 운동화',
        categoryId: 2,
        enrollmentRule: '선착순',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '컴퓨터:월요일A반',
            location: '컴퓨터실',
            capacity: 30,
            allowedGrades: '1~6',
            weekday: '월',
            start: '1:00pm',
            end: '4:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '컴퓨터:화요일A반',
            location: '컴퓨터실',
            capacity: 30,
            allowedGrades: '1~6',
            weekday: '화',
            start: '1:00pm',
            end: '4:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '컴퓨터:수요일A반',
            location: '컴퓨터실',
            capacity: 30,
            allowedGrades: '1~6',
            weekday: '수',
            start: '1:00pm',
            end: '4:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '컴퓨터:목요일A반',
            location: '컴퓨터실',
            capacity: 30,
            allowedGrades: '1~6',
            weekday: '목',
            start: '1:00pm',
            end: '4:20pm',
          },
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '컴퓨터:금요일A반',
            location: '컴퓨터실',
            capacity: 30,
            allowedGrades: '1~6',
            weekday: '금',
            start: '1:00pm',
            end: '4:20pm',
          },
        ],
      },
      {
        lessonName: '축구(1)',
        description: '축구',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '축구(1):화요일반',
            location: '체육관',
            capacity: 0,
            allowedGrades: '1',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '음악줄넘기(1)',
        description: '음악줄넘기',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '미정',
            instructorPhone: '01000000000',
            groupName: '음악줄넘기(1):화요일반',
            location: '체육관',
            capacity: 0,
            allowedGrades: '1',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '창의교실A',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '강희숙',
            instructorPhone: '01000000001',
            groupName: '창의교실A:월요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '월',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '강희숙',
            instructorPhone: '01000000001',
            groupName: '창의교실A:화요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '화',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '강희숙',
            instructorPhone: '01000000001',
            groupName: '창의교실A:수요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '수',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '강희숙',
            instructorPhone: '01000000001',
            groupName: '창의교실A:목요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '목',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '강희숙',
            instructorPhone: '01000000001',
            groupName: '창의교실A:금요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '금',
            start: '1:20pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '창의교실B',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '마선희',
            instructorPhone: '01000000002',
            groupName: '창의교실B:월요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '월',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '마선희',
            instructorPhone: '01000000002',
            groupName: '창의교실B:화요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '화',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '마선희',
            instructorPhone: '01000000002',
            groupName: '창의교실B:수요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '수',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '마선희',
            instructorPhone: '01000000002',
            groupName: '창의교실B:목요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '목',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '마선희',
            instructorPhone: '01000000002',
            groupName: '창의교실B:금요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '금',
            start: '1:20pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '창의교실C',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '탁은혜',
            instructorPhone: '01000000003',
            groupName: '창의교실C:월요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '월',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '탁은혜',
            instructorPhone: '01000000003',
            groupName: '창의교실C:화요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '화',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '탁은혜',
            instructorPhone: '01000000003',
            groupName: '창의교실C:수요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '수',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '탁은혜',
            instructorPhone: '01000000003',
            groupName: '창의교실C:목요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '목',
            start: '1:20pm',
            end: '3:20pm',
          },
          {
            instructorName: '탁은혜',
            instructorPhone: '01000000003',
            groupName: '창의교실C:금요일반',
            location: '1학년교실',
            capacity: 0,
            allowedGrades: '1',
            weekday: '금',
            start: '1:20pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '놀이교실A',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '김정이',
            instructorPhone: '01000000004',
            groupName: '놀이교실A:월요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '김정이',
            instructorPhone: '01000000004',
            groupName: '놀이교실A:화요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '김정이',
            instructorPhone: '01000000004',
            groupName: '놀이교실A:수요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '수',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '김정이',
            instructorPhone: '01000000004',
            groupName: '놀이교실A:목요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '목',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '김정이',
            instructorPhone: '01000000004',
            groupName: '놀이교실A:금요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '금',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '놀이교실B',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '구현미',
            instructorPhone: '01000000005',
            groupName: '놀이교실B:월요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '구현미',
            instructorPhone: '01000000005',
            groupName: '놀이교실B:화요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '구현미',
            instructorPhone: '01000000005',
            groupName: '놀이교실B:수요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '수',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '구현미',
            instructorPhone: '01000000005',
            groupName: '놀이교실B:목요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '목',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '구현미',
            instructorPhone: '01000000005',
            groupName: '놀이교실B:금요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '금',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '놀이교실C',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '정경임',
            instructorPhone: '01000000006',
            groupName: '놀이교실C:월요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '월',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '정경임',
            instructorPhone: '01000000006',
            groupName: '놀이교실C:화요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '화',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '정경임',
            instructorPhone: '01000000006',
            groupName: '놀이교실C:수요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '수',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '정경임',
            instructorPhone: '01000000006',
            groupName: '놀이교실C:목요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '목',
            start: '2:40pm',
            end: '3:20pm',
          },
          {
            instructorName: '정경임',
            instructorPhone: '01000000006',
            groupName: '놀이교실C:금요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '금',
            start: '2:40pm',
            end: '3:20pm',
          },
        ],
      },
      {
        lessonName: '놀이교실D',
        description: '음악,신체,전래,미술,창의 놀이',
        instructorFee: 30000,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 1,
        enrollmentRule: '누구나',
        groups: [
          {
            instructorName: '미확정',
            instructorPhone: '01000000007',
            groupName: '놀이교실D:월요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '월',
            start: '1:50pm',
            end: '2:30pm',
          },
          {
            instructorName: '미확정',
            instructorPhone: '01000000007',
            groupName: '놀이교실D:화요일반',
            location: '2학년교실',
            capacity: 0,
            allowedGrades: '2',
            weekday: '화',
            start: '1:50pm',
            end: '2:30pm',
          },
        ],
      },
    ],
  },
  {
    uri: `schools/1/terms/1/offerings/bulk`,
    payload: {},
  },
  {
    uri: `schools`,
    payload: {
      name: '삼척초등학교',
      authorityCode: 'K10',
      region: 'GANGWON',
      schoolCode: '7872025',
      address: '강원특별자치도 삼척시 일반로 273',
    },
  },
];

async function loginAndGetToken() {
  const res = await fetch(`${url}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: '01094867415',
      password: 'password',
      role: 'PARENT',
    }),
  });

  const data = await res.json();
  return data.accessToken; // 실제 응답 구조에 따라 조정
}

async function run() {
  const token = await loginAndGetToken();
  console.log('✅ token', token);
  for (const item of data) {
    console.log('✅ item', `${url}/${item.uri}`, JSON.stringify(item.payload));
    try {
      const response = await fetch(`${url}/${item.uri}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(item.payload),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(
          `❌ Error for studentId ${item.studentId}:`,
          response.status,
          errorText,
        );
      } else {
        const result = await response.json();
        console.log(`✅ Success for studentId ${item.studentId}:`, result);
      }
    } catch (err) {
      console.error(
        `❗ Network error for studentId ${item.studentId}:`,
        err.message,
      );
    }
  }
}

run();
