/**
 * 자동화 입력 스크립트
 * how to execute? `node db-seed.js`
 */

const url = 'http://localhost:3001/v1';
const data = [
  // {
  //   uri: `schools`,
  //   payload: {
  //     name: '삼척초등학교',
  //     authorityCode: 'K10',
  //     phone: '0335728662', // 삼척초등학교
  //     region: 'GANGWON', // 삼척초등학교
  //     schoolCode: '7872025', // 삼척초등학교
  //     address: '강원특별자치도 삼척시 교동로 100',
  //   },
  // },
  {
    uri: `terms`,
    payload: {
      schoolId: 1,
      schoolYear: 2025,
      schoolName: '신동초등학교',
      termName: '2학기',
      start: '2025-09-01',
      end: '2025-11-30',
    },
  },
  {
    uri: `schools/1/terms/2/lessons/bulk`,
    payload: [
      {
        lessonName: '수사반장',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이무기',
            instructorPhone: '01040128691',
            groupName: '수사반장A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이무기',
            instructorPhone: '01040128691',
            groupName: '수사반장B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '인공지능',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '최불암',
            instructorPhone: '010-2421-5378',
            groupName: '인공지능A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '최불암',
            instructorPhone: '010-2421-5375',
            groupName: '인공지능B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '미스트롯',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이시양',
            instructorPhone: '010-8795-7632',
            groupName: '미스트롯A반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이시양',
            instructorPhone: '010-8795-7632',
            groupName: '미스트롯B반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '방송댄스',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '길수한',
            instructorPhone: '010-2870-7718',
            groupName: '방송댄스A반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '길수한',
            instructorPhone: '010-2870-7718',
            groupName: '방송댄스B반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '배드민턴',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '엄승열',
            instructorPhone: '010-8790-7088',
            groupName: '배드민턴A반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '엄승열',
            instructorPhone: '010-8790-7088',
            groupName: '배드민턴A반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '엄승열',
            instructorPhone: '010-8790-7088',
            groupName: '배드민턴B반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '엄승열',
            instructorPhone: '010-8790-7088',
            groupName: '배드민턴B반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
        ],
      },
      {
        lessonName: '이스포츠',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '김혜수',
            instructorPhone: '010-1116-9603',
            groupName: '이스포츠 (월)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김혜수',
            instructorPhone: '010-1116-9603',
            groupName: '이스포츠 (수)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '요리교실',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '오정상',
            instructorPhone: '010-4343-0066',
            groupName: '요리교실A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
          {
            instructorName: '오정상',
            instructorPhone: '010-4343-0066',
            groupName: '요리교실B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
        ],
      },
      {
        lessonName: '쿠팡알바',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이재명',
            instructorPhone: '010-6666-5388',
            groupName: '쿠팡알바A',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이재명',
            instructorPhone: '010-6666-5388',
            groupName: '쿠팡알바B',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '창의과학',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '육영수',
            instructorPhone: '010-9288-7204',
            groupName: '창의과학A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
          {
            instructorName: '육영수',
            instructorPhone: '010-9288-7204',
            groupName: '창의과학B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
        ],
      },
      {
        lessonName: '유튜브쇼츠',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '박민주',
            instructorPhone: '010-2014-6699',
            groupName: '유튜브쇼츠A',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '수',
            start: '13:10',
            end: '14:10',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
          {
            instructorName: '박민주',
            instructorPhone: '010-2014-6699',
            groupName: '유튜브쇼츠B',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:15',
            end: '15:15',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
        ],
      },
      {
        lessonName: '승마',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '임수창',
            instructorPhone: '010-1117-9630',
            groupName: '승마A반 (월)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '임수창',
            instructorPhone: '010-1117-9630',
            groupName: '승마A반 (수)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '수',
            start: '13:10',
            end: '14:10',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '임수창',
            instructorPhone: '010-1117-9630',
            groupName: '승마B반 (월)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '임수창',
            instructorPhone: '010-1117-9630',
            groupName: '승마B반 (수)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:15',
            end: '15:15',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '주식시장',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '주식시장A반 (화)',
            location: '주식시장실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '주식시장A반 (목)',
            location: '주식시장실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '주식시장B반 (화)',
            location: '주식시장실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '주식시장B반 (목)',
            location: '주식시장실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '수다떨기',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '김정연',
            instructorPhone: '010-3737-5958',
            groupName: '수다떨기A',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 9000,
          },
          {
            instructorName: '김정연',
            instructorPhone: '010-3737-5958',
            groupName: '수다떨기B',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 9000,
          },
        ],
      },
      {
        lessonName: 'KPOP',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '배수구',
            instructorPhone: '010-6222-8611',
            groupName: 'KPOP',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '4~6',
            weekday: '수',
            start: '14:00',
            end: '15:20',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
    ],
  },
  {
    uri: `schools/1/terms/2/offerings/bulk`,
    payload: {},
  },
  // {
  //   uri: `users`,
  //   payload: {
  //     username: '010-7656-1964',
  //     password: 'password',
  //   },
  // },
];

async function loginAndGetToken() {
  const res = await fetch(`${url}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: 'test@gmail.com',
      password: 'password',
      role: 'MANAGER',
    }),
  });

  const data = await res.json();
  return data.accessToken;
}

async function run() {
  const token = await loginAndGetToken();
  console.log('✅ token', token);

  for (const item of data) {
    console.log('👉 item', `${url}/${item.uri}`, JSON.stringify(item.payload));
    try {
      const response = await fetch(`${url}/${item.uri}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(item.payload),
      });

      if (!response.ok) {
        const message = await response.text();
        console.error(`🟡`, message);
      } else {
        const result = await response.json();
        console.log(`🟢`, result);
      }
    } catch (err) {
      console.log(err);
      console.error(`🔴`, err.message);
    }
  }
}

run();
