/**
 * 자동화 입력 스크립트
 * how to execute? `node db-seed.js`
 */

const url = 'http://localhost:3001/v1';
const data = [
  {
    uri: `terms`,
    payload: {
      schoolId: 1,
      schoolYear: 2025,
      termName: '3학기',
      start: '2025-10-01',
      end: '2026-02-01',
      pickRule: 'FIRST',
    },
  },
  {
    uri: `schools/1/terms/3/lessons/bulk`,
    payload: [
      {
        lessonName: '인스타',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '인도형',
            instructorPhone: '01044448691',
            groupName: '인스타A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '인도형',
            instructorPhone: '01044448691',
            groupName: '인스타B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '주짓수',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '배삼룡',
            instructorPhone: '010-2424-5378',
            groupName: '주짓수A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '배삼룡',
            instructorPhone: '010-2424-5375',
            groupName: '주짓수B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '헤나문신',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '문재앙',
            instructorPhone: '010-8795-7000',
            groupName: '헤나문신A반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '문재앙',
            instructorPhone: '010-8795-7000',
            groupName: '헤나문신B반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '방송댄스',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '육완순',
            instructorPhone: '010-0000-7718',
            groupName: '방송댄스A반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '육완순',
            instructorPhone: '010-0000-7718',
            groupName: '방송댄스B반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '탁구',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '박민규',
            instructorPhone: '010-1111-7088',
            groupName: '탁구A반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '박민규',
            instructorPhone: '010-1111-7088',
            groupName: '탁구A반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '박민규',
            instructorPhone: '010-1111-7088',
            groupName: '탁구B반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '박민규',
            instructorPhone: '010-1111-7088',
            groupName: '탁구B반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
        ],
      },
      {
        lessonName: '킥고잉',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '강수지',
            instructorPhone: '010-1000-9603',
            groupName: '킥고잉 (월)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '강수지',
            instructorPhone: '010-1000-9603',
            groupName: '킥고잉 (수)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '변신교실',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '비정상',
            instructorPhone: '010-2222-0066',
            groupName: '변신교실A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
          {
            instructorName: '비정상',
            instructorPhone: '010-2222-0066',
            groupName: '변신교실B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
        ],
      },
      {
        lessonName: '배달의민족',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '수정인',
            instructorPhone: '010-6666-7777',
            groupName: '배달의민족A',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '수정인',
            instructorPhone: '010-6666-7777',
            groupName: '배달의민족B',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '수리논술',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '박정희',
            instructorPhone: '010-0000-7204',
            groupName: '수리논술A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
          {
            instructorName: '박정희',
            instructorPhone: '010-0000-7204',
            groupName: '수리논술B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
        ],
      },
      {
        lessonName: '틱톡',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '전인권',
            instructorPhone: '010-3333-6699',
            groupName: '틱톡A',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '수',
            start: '13:10',
            end: '14:10',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
          {
            instructorName: '전인권',
            instructorPhone: '010-3333-6699',
            groupName: '틱톡B',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:15',
            end: '15:15',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
        ],
      },
    ],
  },
  {
    uri: `schools/1/terms/3/offerings/bulk`,
    payload: {},
  },
];

async function loginAndGetToken() {
  const res = await fetch(`${url}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: 'test@gmail.com',
      password: 'password',
      role: 'MANAGER',
    }),
  });

  const data = await res.json();
  return data.accessToken;
}

async function run() {
  const token = await loginAndGetToken();
  console.log('✅ token', token);

  for (const item of data) {
    console.log('👉 item', `${url}/${item.uri}`, JSON.stringify(item.payload));
    try {
      const response = await fetch(`${url}/${item.uri}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(item.payload),
      });

      if (!response.ok) {
        const message = await response.text();
        console.error(`🟡`, message);
      } else {
        const result = await response.json();
        console.log(`🟢`, result);
      }
    } catch (err) {
      console.log(err);
      console.error(`🔴`, err.message);
    }
  }
}

run();
