/**
 * 자동화 입력 스크립트
 * how to execute? `node db-seed.js`
 */

const url = 'http://localhost:3001/v1';
const data = [
  {
    uri: `schools`,
    payload: {
      name: '신동초등학교',
      authorityCode: 'K10',
      phone: '0332434302', // 신동초등학교
      region: 'GANGWON', // 신동초등학교
      schoolCode: '7812075', // 신동초등학교
      address: '강원특별자치도 춘천시 닭갈비로 100',
    },
  },
  {
    uri: `terms`,
    payload: {
      schoolId: 1,
      schoolYear: 2025,
      schoolName: '신동초등학교',
      termName: '2학기',
      pickRule: 'FIRST',
      start: '2025-09-01',
      end: '2025-11-30',
    },
  },
  {
    uri: `schools/1/students/bulk/seed`,
    payload: {},
  },
  {
    uri: `categories/seed`,
    payload: {},
  },
  {
    uri: `schools/1/calendars`,
    payload: {},
  },
  {
    uri: `schools/1/terms/1/lessons/bulk`,
    payload: [
      {
        lessonName: '독서논술',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '홍재현',
            instructorPhone: '01040128690',
            groupName: '독서논술A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '홍재현',
            instructorPhone: '01040128690',
            groupName: '독서논술B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '로봇과학',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '김영희',
            instructorPhone: '010-8907-2911',
            groupName: '로봇과학A반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김영희',
            instructorPhone: '010-8907-2911',
            groupName: '로봇과학B반',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '바이올린',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '오진석',
            instructorPhone: '010-9486-7415',
            groupName: '바이올린A반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '오진석',
            instructorPhone: '010-9486-7415',
            groupName: '바이올린B반',
            location: '늘봄선택형교실1',
            capacity: 12,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '방송댄스',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '제이슨',
            instructorPhone: '010-2044-0571',
            groupName: '방송댄스A반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '금',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '제이슨',
            instructorPhone: '010-2044-0571',
            groupName: '방송댄스B반',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '금',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '배드민턴',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '김민지',
            instructorPhone: '010-9392-4027',
            groupName: '배드민턴A반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '김민지',
            instructorPhone: '010-9392-4027',
            groupName: '배드민턴A반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '김민지',
            instructorPhone: '010-9392-4027',
            groupName: '배드민턴B반 (화)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
          {
            instructorName: '김민지',
            instructorPhone: '010-9392-4027',
            groupName: '배드민턴B반 (목)',
            location: '체육관',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 3000,
          },
        ],
      },
      {
        lessonName: '사물놀이',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '김혜영',
            instructorPhone: '010-9770-9603',
            groupName: '사물놀이 (월)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김혜영',
            instructorPhone: '010-9770-9603',
            groupName: '사물놀이 (수)',
            location: '음악실',
            capacity: 20,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '요리교실',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이명아',
            instructorPhone: '010-4343-0058',
            groupName: '요리교실A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
          {
            instructorName: '이명아',
            instructorPhone: '010-4343-0058',
            groupName: '요리교실B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 13000,
          },
        ],
      },
      {
        lessonName: '음악줄넘기',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이효진',
            instructorPhone: '010-9142-5388',
            groupName: '음악줄넘기A',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이효진',
            instructorPhone: '010-9142-5388',
            groupName: '음악줄넘기B',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '창의과학',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '이육영',
            instructorPhone: '010-9478-7204',
            groupName: '창의과학A',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
          {
            instructorName: '이육영',
            instructorPhone: '010-9478-7204',
            groupName: '창의과학B',
            location: '늘봄선택형교실2',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 12000,
          },
        ],
      },
      {
        lessonName: '창의미술',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '박은영',
            instructorPhone: '010-2014-1887',
            groupName: '창의미술A',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '수',
            start: '13:10',
            end: '14:10',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
          {
            instructorName: '박은영',
            instructorPhone: '010-2014-1887',
            groupName: '창의미술B',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:15',
            end: '15:15',
            tuition: 70000,
            bookFee: 0,
            materialFee: 4000,
          },
        ],
      },
      {
        lessonName: '축구/풋살',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '이주현',
            instructorPhone: '010-8191-9630',
            groupName: '축구/풋살A반 (월)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이주현',
            instructorPhone: '010-8191-9630',
            groupName: '축구/풋살A반 (수)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '수',
            start: '13:10',
            end: '14:10',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이주현',
            instructorPhone: '010-8191-9630',
            groupName: '축구/풋살B반 (월)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '이주현',
            instructorPhone: '010-8191-9630',
            groupName: '축구/풋살B반 (수)',
            location: '운동장',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '수',
            start: '14:15',
            end: '15:15',
            tuition: 70000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '컴퓨터',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 2,
        groups: [
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '컴퓨터A반 (화)',
            location: '컴퓨터실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '화',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '컴퓨터A반 (목)',
            location: '컴퓨터실',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '목',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '컴퓨터B반 (화)',
            location: '컴퓨터실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '화',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
          {
            instructorName: '김선미',
            instructorPhone: '010-9194-5009',
            groupName: '컴퓨터B반 (목)',
            location: '컴퓨터실',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '목',
            start: '15:05',
            end: '16:05',
            tuition: 60000,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
      {
        lessonName: '토탈공예',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '박정연',
            instructorPhone: '010-3737-6198',
            groupName: '토탈공예A',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '1~2',
            weekday: '월',
            start: '14:00',
            end: '15:00',
            tuition: 60000,
            bookFee: 0,
            materialFee: 9000,
          },
          {
            instructorName: '박정연',
            instructorPhone: '010-3737-6198',
            groupName: '토탈공예B',
            location: '늘봄선택형교실3',
            capacity: 16,
            allowedGrades: '3~6',
            weekday: '월',
            start: '15:05',
            end: '16:05',
            tuition: 70000,
            bookFee: 0,
            materialFee: 9000,
          },
        ],
      },
      {
        lessonName: '연극',
        description: '',
        instructorFee: 0,
        bookFees: [],
        materialFees: [],
        note: '',
        categoryId: 4,
        frequency: 1,
        groups: [
          {
            instructorName: '배영규',
            instructorPhone: '010-6202-8611',
            groupName: '연극',
            location: '체육활동실',
            capacity: 16,
            allowedGrades: '4~6',
            weekday: '수',
            start: '14:00',
            end: '15:20',
            tuition: 0,
            bookFee: 0,
            materialFee: 0,
          },
        ],
      },
    ],
  },
  {
    uri: `schools/1/terms/1/offerings/bulk`,
    payload: {},
  },
  {
    uri: `users`,
    payload: {
      username: '010-8907-2911',
      password: 'password',
    },
  },
  {
    uri: `users`,
    payload: {
      username: '010-9486-7415',
      password: 'password',
    },
  },
  {
    uri: `users`,
    payload: {
      username: '01020440571',
      password: 'password',
    },
  },
  {
    uri: `users`,
    payload: {
      username: '010-9392-4027',
      password: 'password',
    },
  },
];

async function loginAndGetToken() {
  const res = await fetch(`${url}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: 'test@gmail.com',
      password: 'password',
      role: 'MANAGER',
    }),
  });

  const data = await res.json();
  return data.accessToken;
}

async function run() {
  const token = await loginAndGetToken();
  console.log('✅ token', token);

  for (const item of data) {
    console.log('👉 item', `${url}/${item.uri}`, JSON.stringify(item.payload));
    try {
      const response = await fetch(`${url}/${item.uri}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(item.payload),
      });

      if (!response.ok) {
        const message = await response.text();
        console.error(`🟡`, message);
      } else {
        const result = await response.json();
        console.log(`🟢`, result);
      }
    } catch (err) {
      console.log(err);
      console.error(`🔴`, err.message);
    }
  }
}

run();
