services:
  localstack:
    image: localstack/localstack:4.5.0
    container_name: localstack
    ports:
      - "4566:4566"           # LocalStack Gateway
      - "4510-4559:4510-4559" # 외부 서비스 포트 범위
    environment:
      - SERVICES=sqs,events,lambda,dynamodb,firehose,s3,cloudfront,cloudwatch,secretsmanager,logs,apigateway
      - ENFORCE_IAM=0
      - DYNAMODB_SHARE_DB=1
      - DEBUG=1
      - PERSISTENCE=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_SKIP_SIGNATURE_VALIDATION=1
      - LOCALSTACK_HOST=localhost
    volumes:
      - /Users/Shared/docker/localstack-data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - /Users/Shared/docker/redis-data:/data
    networks:
      - app-network

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: school
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    volumes:
      - /Users/Shared/docker/mysql-data:/var/lib/mysql
    networks:
      - app-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    ports:
      - "2306:3306"  # 호스트의 2306 포트를 컨테이너의 3306 포트에 매핑
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: v2
      MARIADB_USER: maria
      MARIADB_PASSWORD: secret
    volumes:
      - /Users/Shared/docker/mariadb-data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - /Users/Shared/docker/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - TZ=UTC
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
