export enum DocumentType {
  RESUME = '이력서',
  CAREER_CERTIFICATE = '경력증명서',
  ID_COPY = '신분증사본',
  PERSONAL_INFO_AGREEMENT = '개인정보제공동의서',
  INSTRUCTOR_BANK_COPY = '강사통장사본',
  MEDICAL_EXAM_CERTIFICATE = '채용신체검사서',
  CRIMINAL_HISTORY_CHECK = '성범죄경력및아동학대관련범죄전력조회동의서',
  GRADUATION_CERTIFICATE = '졸업증명서',
  QUALIFICATION_CERTIFICATE = '자격증',
  TUBERCULOSIS_TEST_RESULT = '잠복결핵감염검진결과서',
  QUARTERLY_TEACHING_PLAN = '분기지도계획서',
  ANNUAL_OPERATION_PLAN = '연간운영계획서',
  COURSE_PREVIEW_VIDEO = '강좌맛보기영상',
  COURSE_PROMO_FLYER = '강좌홍보전단',
  TEACHING_MATERIAL_REVIEW = '교재교구심의서',
  TEACHING_MATERIAL_USAGE_PLAN = '교구교재활용계획서',
  EXHIBITION_PHOTO_1 = '작품전시회사진1',
  EXHIBITION_PHOTO_2 = '작품전시회사진2',
  COURSE_PROMO_VIDEO = '강좌홍보영상',
  ESTIMATE_DOCUMENT = '견적서',
  BUSINESS_REGISTRATION = '사업자등록증',
  PUBLISHER_BANK_COPY = '출판사통장사본',
  INTEGRITY_PLEDGE = '청렴서약서',
  INTEGRITY_CONTRACT_PLEDGE = '청렴계약이행서약서',
  ACCEPTANCE_CONDITIONS = '승낙사항',
  PRIVATE_CONTRACT_MEMO = '수의계약각서',
  PRIVATE_CONTRACT_CONFIRMATION = '수의계약체결여부확인서',
  TAX_EVASION_AFFIDAVIT = '조세포탈관련결격사유각서',
  NATIONAL_TAX_CERTIFICATE = '국세납세증명서',
  SOCIAL_INSURANCE_CERTIFICATE = '4대보험완납증명서',
  PUBLISHER_REGISTRATION = '출판사신고증',
  LOCAL_TAX_CERTIFICATE = '지방세완납증명서',
  VENDOR_INFO_AGREEMENT = '거래처정보수집동의서',
}

//? ex) DocumentTypeLabels[DocumentType.RESUME] returns "이력서"
export const DocumentTypeLabels: Record<DocumentType, string> = {
  [DocumentType.RESUME]: '이력서',
  [DocumentType.CAREER_CERTIFICATE]: '경력증명서',
  [DocumentType.ID_COPY]: '신분증사본',
  [DocumentType.PERSONAL_INFO_AGREEMENT]: '개인정보제공동의서',
  [DocumentType.INSTRUCTOR_BANK_COPY]: '강사통장사본',
  [DocumentType.MEDICAL_EXAM_CERTIFICATE]: '채용신체검사서',
  [DocumentType.CRIMINAL_HISTORY_CHECK]:
    '성범죄경력및아동학대관련범죄전력조회동의서',
  [DocumentType.GRADUATION_CERTIFICATE]: '졸업증명서',
  [DocumentType.QUALIFICATION_CERTIFICATE]: '자격증',
  [DocumentType.TUBERCULOSIS_TEST_RESULT]: '잠복결핵감염검진결과서',
  [DocumentType.QUARTERLY_TEACHING_PLAN]: '분기지도계획서',
  [DocumentType.ANNUAL_OPERATION_PLAN]: '연간운영계획서',
  [DocumentType.COURSE_PREVIEW_VIDEO]: '강좌맛보기영상',
  [DocumentType.COURSE_PROMO_FLYER]: '강좌홍보전단',
  [DocumentType.TEACHING_MATERIAL_REVIEW]: '교재교구심의서',
  [DocumentType.TEACHING_MATERIAL_USAGE_PLAN]: '교구교재활용계획서',
  [DocumentType.EXHIBITION_PHOTO_1]: '작품전시회사진1',
  [DocumentType.EXHIBITION_PHOTO_2]: '작품전시회사진2',
  [DocumentType.COURSE_PROMO_VIDEO]: '강좌홍보영상',
  [DocumentType.ESTIMATE_DOCUMENT]: '견적서',
  [DocumentType.BUSINESS_REGISTRATION]: '사업자등록증',
  [DocumentType.PUBLISHER_BANK_COPY]: '출판사통장사본',
  [DocumentType.INTEGRITY_PLEDGE]: '청렴서약서',
  [DocumentType.INTEGRITY_CONTRACT_PLEDGE]: '청렴계약이행서약서',
  [DocumentType.ACCEPTANCE_CONDITIONS]: '승낙사항',
  [DocumentType.PRIVATE_CONTRACT_MEMO]: '수의계약각서',
  [DocumentType.PRIVATE_CONTRACT_CONFIRMATION]: '수의계약체결여부확인서',
  [DocumentType.TAX_EVASION_AFFIDAVIT]: '조세포탈관련결격사유각서',
  [DocumentType.NATIONAL_TAX_CERTIFICATE]: '국세납세증명서',
  [DocumentType.SOCIAL_INSURANCE_CERTIFICATE]: '4대보험완납증명서',
  [DocumentType.PUBLISHER_REGISTRATION]: '출판사신고증',
  [DocumentType.LOCAL_TAX_CERTIFICATE]: '지방세완납증명서',
  [DocumentType.VENDOR_INFO_AGREEMENT]: '거래처정보수집동의서',
};
