export enum Permission {
  ALLOW_INSTRUCTOR_ADD_STUDENT = 'ALLOW_INSTRUCTOR_ADD_STUDENT',
  ALLOW_INSTRUCTOR_DROP_STUDENT = 'ALLOW_INSTRUCTOR_DROP_STUDENT',
  ALLOW_INSTRUCTOR_MODIFY_FEES = 'ALLOW_INSTRUCTOR_MODIFY_FEES',
  ALLOW_STUDENT_ENROLL_OVERLAP = 'ALLOW_STUDENT_ENROLL_OVERLAP',
}
