export enum Region {
  SEOUL = 'seoul',
  BUSAN = 'busan',
  INCHEON = 'incheon',
  ULSAN = 'ulsan',
  DAEJEON = 'daejeon',
  DAEGU = 'daegu',
  GWANGJU = 'gwangju',
  SEJONG = 'sejong',
  GYEONGGI = 'gyeonggi',
  GANGWON = 'gangwon',
  NORTHERN_JEOLLA = 'northernJeolla',
  SOUTHERN_JEOLLA = 'southernJeolla',
  NORTHERN_GYEONGSANG = 'northernGyeongsang',
  SOUTHERN_GYEONGSANG = 'southernGyeongsang',
  NORTHERN_CHUNGCHEONG = 'northernChungcheong',
  SOUTHERN_CHUNGCHEONG = 'southernChungcheong',
  JEJU = 'jeju',
  OTHER = 'other',
}
