export enum SubsidyType {
  BASIC_EDUCATION_RECIPIENT = '기초교육급여수급자',
  BASIC_LIVING_RECIPIENT = '기초생계급여수급자',
  BASIC_MEDICAL_RECIPIENT = '기초의료급여수급자',
  BASIC_HOUSING_RECIPIENT = '기초주거급여수급자',
  INCOME_ASSESSMENT_TARGET = '소득수준조사대상자',
  LOW_INCOME_CERTIFICATE_ELIGIBLE = '차상위계층확인서발급대상자',
  LOW_INCOME_MEDICAL_BENEFIT = '차상위본임부담경감대상자',
  SINGLE_PARENT_ELIGIBLE = '한부모가족보호대상자',
  BELOW_50_MEDIAN_INCOME = '중위소득50%이하',
  BELOW_60_MEDIAN_INCOME = '중위소득60%이하',
  BELOW_80_MEDIAN_INCOME = '중위소득80%이하',
  BELOW_90_MEDIAN_INCOME = '중위소득90%이하',
  PREVIOUS_YEAR_RECIPIENT = '전학년도기지원대상자',
  MULTI_CHILD_FAMILY_SUPPORT = '다자녀가정지원',
  CHILD_OF_BASIC_LIVING_RECIPIENT = '기초생활수급자자녀',
  CHILD_OF_SINGLE_PARENT_ELIGIBLE = '한부모가족보호대상자녀',
  PRIORITY_LOW_INCOME_CARE = '우선돌봄차상위대상자',
  LOW_INCOME_SELF_SUPPORT = '차상위자활급여대상자',
  LOW_INCOME_MEDICAL_SUPPORT = '차상위본인부담경감대상자',
  LOW_INCOME_DISABILITY_ALLOWANCE = '차상위장애수당대상자',
  LOW_INCOME_DISABILITY_PENSION = '차상위장애연금대상자',
  BELOW_120_MINIMUM_COST_OF_LIVING = '최저생계비120%이하',
  BELOW_130_MINIMUM_COST_OF_LIVING = '최저생계비130%이하',
  PRINCIPAL_RECOMMENDED = '학교장추천대상자',
  ORPHAN_OR_HEAD_OF_HOUSEHOLD = '소년소녀가장',
  STUDENT_IN_FACILITY = '시설수용학생',
  CHILD_OF_NATIONAL_MERIT = '보훈대상자자녀',
  CHILD_OF_NORTH_KOREAN_DEFECTOR = '북한이탈주민자녀',
  TEACHER_RECOMMENDED = '기타담임추천대상자',
  FREE_TUITION_ELIGIBLE = '자유수강권대상자',
}

//? ex) SubsidyTypeLabels[SubsidyType.BASIC_LIVING_RECIPIENT] returns "기초생계급여수급자"

export const SubsidyTypeLabels: Record<SubsidyType, string> = {
  [SubsidyType.BASIC_EDUCATION_RECIPIENT]: '기초교육급여수급자',
  [SubsidyType.BASIC_LIVING_RECIPIENT]: '기초생계급여수급자',
  [SubsidyType.BASIC_MEDICAL_RECIPIENT]: '기초의료급여수급자',
  [SubsidyType.BASIC_HOUSING_RECIPIENT]: '기초주거급여수급자',
  [SubsidyType.INCOME_ASSESSMENT_TARGET]: '소득수준조사대상자',
  [SubsidyType.LOW_INCOME_CERTIFICATE_ELIGIBLE]: '차상위계층확인서발급대상자',
  [SubsidyType.LOW_INCOME_MEDICAL_BENEFIT]: '차상위본임부담경감대상자',
  [SubsidyType.SINGLE_PARENT_ELIGIBLE]: '한부모가족보호대상자',
  [SubsidyType.BELOW_50_MEDIAN_INCOME]: '중위소득50%이하',
  [SubsidyType.BELOW_60_MEDIAN_INCOME]: '중위소득60%이하',
  [SubsidyType.BELOW_80_MEDIAN_INCOME]: '중위소득80%이하',
  [SubsidyType.BELOW_90_MEDIAN_INCOME]: '중위소득90%이하',
  [SubsidyType.PREVIOUS_YEAR_RECIPIENT]: '전학년도기지원대상자',
  [SubsidyType.MULTI_CHILD_FAMILY_SUPPORT]: '다자녀가정지원',
  [SubsidyType.CHILD_OF_BASIC_LIVING_RECIPIENT]: '기초생활수급자자녀',
  [SubsidyType.CHILD_OF_SINGLE_PARENT_ELIGIBLE]: '한부모가족보호대상자녀',
  [SubsidyType.PRIORITY_LOW_INCOME_CARE]: '우선돌봄차상위대상자',
  [SubsidyType.LOW_INCOME_SELF_SUPPORT]: '차상위자활급여대상자',
  [SubsidyType.LOW_INCOME_MEDICAL_SUPPORT]: '차상위본인부담경감대상자',
  [SubsidyType.LOW_INCOME_DISABILITY_ALLOWANCE]: '차상위장애수당대상자',
  [SubsidyType.LOW_INCOME_DISABILITY_PENSION]: '차상위장애연금대상자',
  [SubsidyType.BELOW_120_MINIMUM_COST_OF_LIVING]: '최저생계비120%이하',
  [SubsidyType.BELOW_130_MINIMUM_COST_OF_LIVING]: '최저생계비130%이하',
  [SubsidyType.PRINCIPAL_RECOMMENDED]: '학교장추천대상자',
  [SubsidyType.ORPHAN_OR_HEAD_OF_HOUSEHOLD]: '소년소녀가장',
  [SubsidyType.STUDENT_IN_FACILITY]: '시설수용학생',
  [SubsidyType.CHILD_OF_NATIONAL_MERIT]: '보훈대상자자녀',
  [SubsidyType.CHILD_OF_NORTH_KOREAN_DEFECTOR]: '북한이탈주민자녀',
  [SubsidyType.TEACHER_RECOMMENDED]: '기타담임추천대상자',
  [SubsidyType.FREE_TUITION_ELIGIBLE]: '자유수강권대상자',
};
